# Generated by Django 3.1.7 on 2021-04-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('is_exist', models.BooleanField(default=True, verbose_name='is exist:')),
                ('price', models.IntegerField()),
                ('rate', models.CharField(choices=[('sam', 'SAMSUNG'), ('apl', 'APPLE'), ('shi', 'SHIOMI'), ('hoa', 'HOAWEI'), ('nok', 'NOKIA')], max_length=3)),
            ],
        ),
    ]
