# Generated by Django 3.1.7 on 2021-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiZiaApp', '0002_auto_20210426_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='specification',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
