# Generated by Django 3.1.7 on 2021-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiZiaApp', '0003_phone_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image')),
                ('is_exist', models.BooleanField(default=True, verbose_name='is exist:')),
                ('price', models.IntegerField()),
                ('summary', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('is_exist', models.BooleanField(default=True, verbose_name='is exist:')),
                ('price', models.IntegerField()),
                ('brand', models.CharField(choices=[('can', 'CANON'), ('nik', 'NIKON'), ('shi', 'SHIOMI'), ('sam', 'SAMSUNG'), ('son', 'SONY'), ('fuj', 'FUJIFILM')], max_length=3)),
                ('specification', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('is_exist', models.BooleanField(default=True, verbose_name='is exist:')),
                ('price', models.IntegerField()),
                ('brand', models.CharField(choices=[('sam', 'SAMSUNG'), ('apl', 'APPLE'), ('asu', 'ASUS'), ('len', 'LENOVA'), ('hpp', 'HP'), ('hpp', 'DELL'), ('hpp', 'MSI'), ('mic', 'MICROSOFT'), ('ace', 'ACER')], max_length=3)),
                ('specification', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
